version: 2

references:
  # Reusable references that will be used in the jobs
  
jobs:
  ## Run unit tests
  test_unit:
    # ...

  ## Run instrumentation tests
  test_instrumentation:
    # ...

  ## Deploy to Crashlytics Beta
  deploy_crashlytics:
    # ...

workflows:
  version: 2
  workflow:
    jobs:
      # Jobs that will run when you push to your repo ...